
[Settings]
; When enabled, S.L.A.C.K. will make SKSE cosaves save more quickly.
AccelerateSaving = true
; When enabled, S.L.A.C.K. will make SKSE cosaves load more quickly.
AccelerateLoading = true
; When enabled, S.L.A.C.K. will display how long the SKSE cosave took to save when the game is saved.
; This is done even when `AccelerateSaving` is disabled.
LogSaveTimingsToConsole = true
; When enabled, S.L.A.C.K. will display how long the SKSE cosave took to load when a save is loaded.
; This is done even when `AccelerateLoading` is disabled.
LogLoadTimingsToConsole = true
; When enabled, S.L.A.C.K. will catch exceptions thrown by SKSE plugins' cosave handlers,
; like SKSE's original code does.
; This will help to prevent some bugs in plugins from crashing the game when saving and loading,
; but will make it less obvious that said bugs may have silently caused data corruption.
ErrorFriendlyMode = true
; When enabled, S.L.A.C.K. will work around bugs in other mods' usage of SKSE's saving/loading routines.
; This will default to either true or false, depending on if it is needed or not.
WorkAroundThirdPartyBugs =

[Patches]
; When enabled, S.L.A.C.K. will aggregate what would have been a run of
; potentially hundreds, or thousands, of file flushes (while saving or loading)
; into a single file flush in SKSE's saving/loading routines.
AggregateFileFlushingInSKSE = true
; When enabled, S.L.A.C.K. will aggregate what would have been a run of
; potentially hundreds, or thousands, of file flushes (while saving or loading)
; into a single file flush in PapyrusUtil's saving/loading routines.
AggregateFileFlushingInPapyrusUtil = true

[Notifications]
; When enabled, S.L.A.C.K. will display a notification if unrecoverable errors occur while saving.
ShowSavingErrorNotifications = true
; When enabled, S.L.A.C.K. will display a notification if unrecoverable errors occur while loading.
ShowLoadingErrorNotifications = true
; When enabled, S.L.A.C.K. will display a notification if recoverable errors occur while saving.
ShowSavingWarningNotifications = true
; When enabled, S.L.A.C.K. will display a notification if recoverable errors occur while saving.
ShowLoadingWarningNotifications = true
; The sound effect played if an unrecoverable error occurs while saving. Leave this blank for silence.
SavingErrorSound = UILockpickingPickBreak
; The sound effect played if an unrecoverable error occurs while loading. Leave this blank for silence.
LoadingErrorSound = UILockpickingPickBreak
; The sound effect played if a recoverable error occurs while saving. Leave this blank for silence.
SavingWarningSound = UIMenuCancel
; The sound effect played if a recoverable error occurs while loading. Leave this blank for silence.
LoadingWarningSound = UIMenuCancel

[Profiling]
; When enabled, S.L.A.C.K. will log to the console how long each SKSE plugin took to save.
ProfileSaving = false
; When enabled, S.L.A.C.K. will log to the console how long each SKSE plugin took to load.
ProfileLoading = false

[ParallelSaving]
; When enabled, and if `AccelerateSaving` is also enabled,
; multiple threads will be used to save the data of multiple SKSE plugins simultaneously.
; This is experimental. Game crashes may occur during or after saving when this is enabled;
; such is because forcing code which was made to be run only in a single-threaded context
; in a multi-threaded context is inherently unsafe.
;
; Parallel-saving requires Windows 8 or newer.
Enabled = false
; This controls the maximum number of threads to be used for parallel saving.
; If this is not supplied,
; it defaults to the number of logical-cores of the system's processor, or sixteen, whichever is lower.
; This value has a maximum of 128.
ThreadCount =

[SKSE]
; This setting specifies the name of the SKSE DLL that is to be patched at runtime.
; There is no need to set this unless you have renamed your SKSE DLL.
; If this is not provided, it defaults to the expected name of the SKSE DLL,
; which varies by the version of the game, the expected names are as follows:
;       AE 1.7.104: skse64_1_7_104.dll
;        AE 1.7.99: skse64_1_7_99.dll
;      AE 1.6.1170: skse64_1_6_1170.dll
;      AE 1.6.1130: skse64_1_6_1130.dll
;       AE 1.6.640: skse64_1_6_640.dll
;       AE 1.6.353: skse64_1_6_353.dll
;        SE 1.5.97: skse64_1_5_97.dll
;        VR 1.4.15: sksevr_1_4_15.dll
;     GOG 1.6.1179: skse64_1_6_1179.dll
;      GOG 1.6.659: skse64_1_6_659.dll
SKSEDLLName =

